// src/pages/Dashboard.jsx
import React, { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import AppLayout from '@/components/Layout/AppLayout'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { displayApi, slideshowApi } from '@/lib/api'
import { Monitor, Presentation, Plus, Eye, Settings } from 'lucide-react'

export default function Dashboard() {
  const [displays, setDisplays] = useState([])
  const [slideshows, setSlideshows] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadData()
  }, [])

  const loadData = async () => {
    try {
      const [displaysRes, slideshowsRes] = await Promise.all([
        displayApi.getAll(),
        slideshowApi.getAll()
      ])
      setDisplays(displaysRes.data)
      setSlideshows(slideshowsRes.data)
    } catch (error) {
      console.error('Error loading data:', error)
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <AppLayout>
        <div className="flex items-center justify-center h-full">
          <div className="animate-spin rounded-full h-32 w-32 border-b-2 border-primary"></div>
        </div>
      </AppLayout>
    )
  }

  return (
    <AppLayout>
      <div className="p-8">
        <div className="mb-8">
          <h1 className="text-3xl font-bold tracking-tight">Dashboard</h1>
          <p className="text-muted-foreground">
            Manage your digital signage displays and content
          </p>
        </div>

        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          {/* Displays Overview */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
          >
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Total Displays
                </CardTitle>
                <Monitor className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{displays.length}</div>
                <p className="text-xs text-muted-foreground">
                  Active digital displays
                </p>
              </CardContent>
            </Card>
          </motion.div>

          {/* Slideshows Overview */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
          >
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Total Slideshows
                </CardTitle>
                <Presentation className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{slideshows.length}</div>
                <p className="text-xs text-muted-foreground">
                  Content slideshows
                </p>
              </CardContent>
            </Card>
          </motion.div>

          {/* Quick Actions */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
          >
            <Card>
              <CardHeader>
                <CardTitle>Quick Actions</CardTitle>
                <CardDescription>
                  Common tasks and shortcuts
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-2">
                <Link to="/displays">
                  <Button variant="outline" className="w-full justify-start">
                    <Plus className="mr-2 h-4 w-4" />
                    Create Display
                  </Button>
                </Link>
                <Link to="/slideshows">
                  <Button variant="outline" className="w-full justify-start">
                    <Plus className="mr-2 h-4 w-4" />
                    Create Slideshow
                  </Button>
                </Link>
              </CardContent>
            </Card>
          </motion.div>
        </div>

        {/* Recent Displays */}
        <div className="mt-8">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold">Recent Displays</h2>
            <Link to="/displays">
              <Button variant="outline" size="sm">
                View All
              </Button>
            </Link>
          </div>
          
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {displays.slice(0, 6).map((display, index) => (
              <motion.div
                key={display.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.1 * index }}
              >
                <Card className="hover:shadow-md transition-shadow">
                  <CardHeader>
                    <CardTitle className="text-lg">{display.name}</CardTitle>
                    <CardDescription>
                      {display.description || 'No description'}
                    </CardDescription>
                  </CardHeader>
                  <CardContent>
                    <div className="flex space-x-2">
                      <Link to={`/layout/${display.id}`}>
                        <Button size="sm" variant="outline">
                          <Settings className="mr-2 h-4 w-4" />
                          Layout
                        </Button>
                      </Link>
                      <Link to={`/preview/${display.id}`}>
                        <Button size="sm" variant="outline">
                          <Eye className="mr-2 h-4 w-4" />
                          Preview
                        </Button>
                      </Link>
                    </div>
                  </CardContent>
                </Card>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </AppLayout>
  )
}

// frontend/src/views/Dashboard.vue
<template>
  <div class="min-h-screen bg-gray-50">
    <AppLayout>
      <div class="py-6">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="mb-8">
            <h1 class="text-2xl font-bold text-gray-900">Dashboard</h1>
            <p class="mt-1 text-sm text-gray-600">
              Manage your digital signage displays and content
            </p>
          </div>

          <!-- Stats -->
          <div class="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 mb-8">
            <div class="bg-white overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <ComputerDesktopIcon class="h-6 w-6 text-gray-400" />
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-gray-500 truncate">
                        Total Displays
                      </dt>
                      <dd class="text-lg font-medium text-gray-900">
                        {{ displays.length }}
                      </dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-white overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <PresentationChartLineIcon class="h-6 w-6 text-gray-400" />
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-gray-500 truncate">
                        Total Slideshows
                      </dt>
                      <dd class="text-lg font-medium text-gray-900">
                        {{ slideshows.length }}
                      </dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>

            <div class="bg-white overflow-hidden shadow rounded-lg">
              <div class="p-5">
                <div class="flex items-center">
                  <div class="flex-shrink-0">
                    <SignalIcon class="h-6 w-6 text-green-400" />
                  </div>
                  <div class="ml-5 w-0 flex-1">
                    <dl>
                      <dt class="text-sm font-medium text-gray-500 truncate">
                        Online Displays
                      </dt>
                      <dd class="text-lg font-medium text-gray-900">
                        {{ displays.filter(d => d.is_active).length }}
                      </dd>
                    </dl>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Recent Displays -->
          <div class="bg-white shadow rounded-lg">
            <div class="px-4 py-5 sm:p-6">
              <div class="flex items-center justify-between mb-4">
                <h3 class="text-lg leading-6 font-medium text-gray-900">
                  Recent Displays
                </h3>
                <router-link
                  to="/displays"
                  class="text-sm font-medium text-primary-600 hover:text-primary-500"
                >
                  View all
                </router-link>
              </div>
              
              <div v-if="loading" class="text-center py-4">
                <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary-600 mx-auto"></div>
              </div>
              
              <div v-else-if="displays.length === 0" class="text-center py-8">
                <ComputerDesktopIcon class="mx-auto h-12 w-12 text-gray-400" />
                <h3 class="mt-2 text-sm font-medium text-gray-900">No displays</h3>
                <p class="mt-1 text-sm text-gray-500">
                  Get started by creating a new display.
                </p>
                <div class="mt-6">
                  <router-link
                    to="/displays"
                    class="inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-primary-600 hover:bg-primary-700"
                  >
                    <PlusIcon class="-ml-1 mr-2 h-5 w-5" />
                    New Display
                  </router-link>
                </div>
              </div>
              
              <div v-else class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
                <div
                  v-for="display in displays.slice(0, 6)"
                  :key="display.id"
                  class="relative rounded-lg border border-gray-300 bg-white px-6 py-5 shadow-sm flex items-center space-x-3 hover:border-gray-400"
                >
                  <div class="flex-shrink-0">
                    <ComputerDesktopIcon class="h-10 w-10 text-primary-600" />
                  </div>
                  <div class="flex-1 min-w-0">
                    <router-link :to="`/displays/${display.id}/layout`" class="focus:outline-none">
                      <span class="absolute inset-0" />
                      <p class="text-sm font-medium text-gray-900">
                        {{ display.name }}
                      </p>
                      <p class="text-sm text-gray-500 truncate">
                        {{ display.description || 'No description' }}
                      </p>
                    </router-link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </AppLayout>
  </div>
</template>

<script>
import { ref, onMounted } from 'vue'
import { useDisplayStore } from '@/stores/displays'
import AppLayout from '@/components/layout/AppLayout.vue'
import {
  ComputerDesktopIcon,
  PresentationChartLineIcon,
  SignalIcon,
  PlusIcon,
} from '@heroicons/vue/24/outline'

export default {
  name: 'Dashboard',
  components: {
    AppLayout,
    ComputerDesktopIcon,
    PresentationChartLineIcon,
    SignalIcon,
    PlusIcon,
  },
  setup() {
    const displayStore = useDisplayStore()
    const slideshows = ref([])
    const loading = ref(true)

    onMounted(async () => {
      try {
        await displayStore.fetchDisplays()
        // TODO: Fetch slideshows
      } catch (error) {
        console.error('Error loading dashboard data:', error)
      } finally {
        loading.value = false
      }
    })

    return {
      displays: displayStore.displays,
      slideshows,
      loading,
    }
  },
}
</script>
